services:
  postgres:
    image: postgres:15
    container_name: postgres_bratishka
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kirill123
      POSTGRES_DB: bratishka_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
